SoccerScores/Models/ErrorViewModel.cs
using System;

namespace ScoresUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SoccerScores/ViewModels/SoccerScoresViewModel.cs
using Scores.Library.Models.Soccer;
using System.Collections.Generic;

namespace ScoresUI.ViewModels
{
    public class SoccerScoresViewModel
    {
        public List<Competition> Competitions { get; set; }
        public string PageTitle { get; set; }
    }
}

SoccerScores/Controllers/HomeController.cs
using System.Diagnostics;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ScoresUI.Models;

namespace ScoresUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public IHttpClientFactory _HttpClientFactory { get; }

        public HomeController(ILogger<HomeController> logger, IHttpClientFactory httpClientFactory)
        {
            _logger = logger;
            _HttpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SoccerScores/Controllers/SoccerController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Scores.Library.HttpClients.Soccer;
using Scores.Library.Models.Soccer;
using ScoresUI.ViewModels;

namespace ScoresUI.Controllers
{
    public class SoccerController : Controller
    {
        
        private readonly ILogger<SoccerController> _logger;
        private readonly ISoccerClient _soccerClient;
        private readonly IConfiguration _config;

        public SoccerController(ILogger<SoccerController> logger, ISoccerClient soccerClient, IConfiguration config)
        {
            _soccerClient = soccerClient;
            _config = config;
            _logger = logger;
        }
        public async Task<ViewResult> GetCompetitions()
        {
            var data = await _soccerClient.SoccerCompetitions();

            SoccerScoresViewModel competitionCollectionViewModel = new SoccerScoresViewModel();

            competitionCollectionViewModel.Competitions = AddCompetitionLogo(data);
            competitionCollectionViewModel.PageTitle = "Soccer Competitions";


            return View(competitionCollectionViewModel);


        }

        // Move to library
        private Dictionary<string, string> LoadLogos()
        {
            return _config.GetSection("SoccerCompetitionLogos").Get<Dictionary<string, string>>();
        }

        private List<Competition> AddCompetitionLogo(List<Competition> competitions)
        {
            List<Competition> data = new List<Competition>(competitions);

            Dictionary<string, string> logos = LoadLogos();

            foreach (Competition comp in data)
            {
                if (String.IsNullOrEmpty(comp.emblemUrl))
                {
                    if (logos.ContainsKey(comp.code))
                    {
                        comp.emblemUrl = logos[comp.code];
                    }
                }
            }

            return data; 
        }
    }
}

SoccerScores/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Sport Scores Home ";
}

    
        <div class="text-center">
            <h1 class="display-4">Welcome to Sports Scores</h1>
        </div>
    

SoccerScores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <title>@ViewData["Title"] - Sports Scores</title>
</head>
<body>
    <div id="BackgroundPic">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sports Scores</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Soccer" asp-action="GetCompetitions">Soccer Scores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - Sports Scores - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>

SoccerScores/Views/Soccer/GetCompetitions.cshtml
@model ScoresUI.ViewModels.SoccerScoresViewModel

<title>@Model.PageTitle</title>

<h3 class="promo-title text-center">Soccer Competitions</h3>
<h2 class="promo-description text-center">Access to data of these leagues & cups.</h2>


<div class="card-deck">

    @foreach (var competition in Model.Competitions)
    {
        

    <div class="card m-3" style="min-width: 18rem; max-width: 30.5%">
        <div class="card-header text-center">
            <h3>@competition.name</h3>
            <h2>@competition.area.name</h2>
        </div>
        
        <img class="card-img-top img-thumbnail" src="@competition.emblemUrl" alt=url("../images/No-image-available.png") asp-append-version="true" />
        <div class="brand-item-footer helper center">
            <div class="card-footer text-center">
                <a href="#" class="btn-primary m1">Latest Matches</a>
            </div>
        </div>
    </div>


    }
</div>